baseurl = "http://https://lalde.github.io/"
title = "Lucie Descamps"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = '<!--[-->PhD Candidate at the <a href="https://www.ntnu.edu/kavli">Kavli Institute for Systems Neuroscience</a>, NTNU, Norway <!--]--><br />
                <!--[--><!--]-->'
  logo = "fa-flask"
  copyright = "Untitled"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/luciealdescamps"


[languages]
[languages.en]
languageName = "English"
weight = 1

[languages.fr]
languageName = "Français"
weight = 2
description = '<!--[-->Etudiante en thèse au <a href="https://www.ntnu.edu/kavli">Kavli Institute for Systems Neuroscience</a>, NTNU, Norvège <!--]--><br />
              <!--[--><!--]-->'
